### ISSUE TITLE
Percent-encoded paths are not handled correctly

### ISSUE THREAD

**Issue by malaire** [ibraheemdev/httprouter-rs#1]
Here's two failing examples:
```rust
use http::Method;
use httprouter::Router;

fn main() {
    let mut router = Router::default();
    router.get("/foo%2Fbar", "Hello");
    router.get("/foo bar", "Hello");

    assert_eq!(
        router.lookup(&Method::GET, "/foo%2fbar").unwrap().value,
        &"Hello"
    );

    assert_eq!(
        router.lookup(&Method::GET, "/foo%20bar").unwrap().value,
        &"Hello"
    );
}
```

**Comment by ibraheemdev** [comment]
I'll look into this issue.

**Comment by robjtede** [comment]
According to RFC 3986, `/foo bar` should not be implicitly accepted since space is neither unreserved nor escaped.

**Comment by ibraheemdev** [comment]
Yes, `/foo bar` will not be handled implicitly. You must escape the space when adding it to the router:
```rust
use http::Method;
use httprouter::Router;

fn main() {
    let mut router = Router::default();
    router.get("/foo%20bar", "Hello");

    assert_eq!(
        router.lookup(&Method::GET, "/foo%20bar").unwrap().value,
        &"Hello"
    );
}
```

**Comment by ibraheemdev** [comment]
As for your first example, you added the route `/foo%2Fbar`, but looked up `/foo%2fbar`; notice the capitalization of the `f`. Either you can add and lookup the routes with the same case, or you can make a case insensitive lookup.

**Comment by malaire** [comment]
> As for your first example, you added the route /foo%2Fbar, but looked up /foo%2fbar; notice the capitalization of the f. Either you can add and lookup the routes with the same case, or you can make a case insensitive lookup.

You don't understand: `%2F` and `%2f` must match each other (but not `/`) when using URLs. This is said in RFC 3986.

**Comment by malaire** [comment]
Another example: If I insert route `/%7efoo`, then all of these must match it: `/~foo`, `/%7efoo`, `/%7Efoo`

ps. yes, the space was bad example, `~` is better.

**Comment by ibraheemdev** [comment]
I think it makes sense to add this functionality to this crate. It should be as simple as [decoding](https://docs.rs/percent-encoding/2.1.0/percent_encoding/fn.percent_decode.html) the url path before inserting a route in the tree, and before performing a lookup.

**Comment by malaire** [comment]
It's not quite that simple, because you can't just decode `/foo%2Fbar` to `/foo/bar` as those must be handled differently.

I think correct solution is to convert URL to so called "serialized form" because according to standard, in serialized form URLs can be compared directly. I've opened issue about this at `url` crate which says it's doing the serialization according to standard, but to me it looks to be buggy: https://github.com/servo/rust-url/issues/664

URL serialization is quite tricky so I think it should be handled by specialized crate like `url` (and when done correctly this will also handle cases like `/foo/../bar` being equal to `/bar` which I don't care that much, but would be nice to have).

**Comment by ibraheemdev** [comment]
I'll look into using the `url` crate. Also, `/foo/../bar` is already being handled by `path::clean_path`.

**Comment by malaire** [comment]
I got answer from WHATWG member in issue https://github.com/whatwg/url/issues/565 and it looks like I was wrong here: Current URL spec differs drastically from older RFC 3986 in how such URLs should be handled. According to current spec percent-decoding is **not** done for URLs when determining whether URLs are equivalent.
